### ISSUE TITLE
Deleting a Project in issueSHARK does not remove related issue data in mongo db

### ISSUE THREAD

**Issue by iwonajs** [smartshark/serverSHARK#39]
1. created a project 'zookeeper' in issuesSHARK
2. used plugin issuesSHARK to start downloading issue data
3. deleted the project issuesSHARK in the issuesSHARK
Expected: all the related issues would have been removed from the mongoDB
Actual: Viewing mongoDB collections "issues" I see issues with ZOOKEEPER-IDs
issues.issue_system_id = 5f2469cd44d7ac083dbfca79
this is the 'zookeeper' project id which no longer exists in the collections.projects._id

**Comment by iwonajs** [comment]
I do see that there is an option to remove data for a project without removing the project itself.
I just assumed that removing the project would invoke that as well.

**Comment by atrautsch** [comment]
There is a delete_project command which deletes everything for one project. It is not in the admin UI because this is potentially a lengthy process for which we have not yet implemented an offload to the worker process. Without it the time it takes to delete a project would exceed certain timeouts for requests, e.g., from the webserver.
