### ISSUE TITLE
About the commit verification feature

### ISSUE THREAD

**Issue by yiikou** [smartshark/serverSHARK#42]
Hi, I notce that there is a commit verification functionality and I'm curious about it since there is no trigger is observed. Is this verification designed for monitoring new commit?

**Comment by atrautsch** [comment]
The feature was used to cross check our HPC system. It locally checks out the repository and checks if every file of every commit is in the database and if it contains mecoSHARK and coastSHARK metrics.
There are a couple of commands that can be used for that, create_verification_data creates a list of commits for a project and verify_project does the verification.
It should not be necessary in most cases.

**Comment by yiikou** [comment]
Thanks for the explanation. Are there any instruction or brief explanation on HPC system? As I guess, the configuration is in the `server/setting.py`, and the usage might related to `http://0.0.0.0:8001/spark/submit/`?

**Comment by sherbold** [comment]
The Spark parts are currently not used. Theoretically, you could use that to connect a spark cluster that can run analytics on the MongoDB. 

The HPC feature requires that you have an HPC system available. We currently only support slurm as job scheduler for the HPC system. If you have such a system that you could use, you should first get familiar with the usage of that system. Afterwards, you could consider to tailor the HPC backend to your service provide, because aspects like storage may differ from our configuration.

**Comment by yiikou** [comment]
@sherbold thanks for the explanation.

**Comment by yiikou** [comment]
Hi @sherbold, I would like to ask four follow-up questions regarding HPC system:
1) is the db still central db? or distributed db.
2) how do you deal with the i/o transaction. For example, for the same project, there are multiple plugins are running and some of them will write into the same collection.
3) How to install plugins for HPC system. My assumption is via 
![image](https://user-images.githubusercontent.com/6872777/99726627-b2475100-2a84-11eb-97d7-eb84d87d53da.png). 
4) How servershark interact with slurm? 

Thank you.

**Comment by atrautsch** [comment]
Hi, I can also answer this.
1. The database is a central db, we did some collection with a sharded mongodb but right now we have one central db.
2. At the moment we only run one plugin per project, the system was originally build to run multiple plugins in sequence of the dependencies but we found that in a batch system there may be errors occurring which we have to address first before running the next plugin. For now we run one plugin per project.
3. This is triggered via the install plugin action on the plugin page. The HPC Connector handles copying the plugin and running the install.sh script on the HPC System.
4. The idea is that the job submission backend does not matter so the workflow is the same for local queue as for the HPC System.
However, we only have one HPC System and there could be issues running on another system with our connector implementation.
5. The Slurm interaction is for now limited to job submission and iirc we can manually update the job status, however there we are also using a mount from the home folder of our HPC user to directly look at the job logs. We migrated from the IBM system to Slurm so this is somewhat rudimentary.

**Comment by yiikou** [comment]
Hi @atrautsch , with further understanding towards serverSHARK, I was wondering that what are the advantages of using HPC, comparing using Spark for data collection and enhancing. If only use one backend, will it make the system easier to maintain?

Thank you.

**Comment by atrautsch** [comment]
HI @yiikou 
The difference between HPC and Spark in our case was always data collection and  data analytics.
While we could implement everything in Spark there are some considerations restrict the choice of the execution backend.

1) Simplicity
We try to keep the plugins as simple as possible, ultimately we would like every one to be executable without serverSHARK.
While there are obvious limitations due to dependencies this is a factor that is important to us.

2) Portability
This basically results from 1). We have the ability now to switch out the execution backend without having to change the plugins at all as they can be run from the command line. This allows us to distribute the serverSHARK with a working local queue via Redis as execution backend.

While Spark is great to really make use of it we would have to change the plugins to get the SparkContext and really make use of the Spark API.

**Comment by yiikou** [comment]
Thanks for the explanation, really appreciate it!
